fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\UserManagement\User
    use_flash_notifications: false
    service:
        mailer: App\Mailer\Mailjet
    from_email:
        address: '%env(MAILER_USER)%'
        sender_name: '%env(MAILER_USER)%'
    registration:
        form:
            type: App\Form\RegistrationType
        confirmation:
            enabled: true
    profile:
        form:
            type: App\Form\ProfileType
