fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:
        fr: '/fr'
        en: '/en'

fos_user_registration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:
        fr: '/fr/register'
        en: '/en/register'

fos_user_resseting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix:
        fr: '/fr/resetting'
        en: '/en/resetting'
