conditions:
    path:          /conditions
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template:  'static/conditions.html.twig'
        maxAge:    86400
        sharedAge: 86400

mentions:
    path:          /mentions
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template:  'static/mentions.html.twig'
        maxAge:    86400
        sharedAge: 86400

dash:
    path:          /admin/dash
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template:  'static/dash.html.twig'
        maxAge:    86400
        sharedAge: 86400
